id: TXPipe
#this step depends on where you run
#for CCin2p3
site:
    name: local
    max_threads: 60
#site:
#    name: cori-batch
#    image: ghcr.io/lsstdesc/txpipe-dev
#all the following steps should not depend on where you run
launcher:
    name: mini
    interval: 0.5
modules: >
    txpipe
    txpipe.extensions
    rail.estimation.algos.bpz_lite
python_paths: []
stages:
  - name: TXSourceSelectorMetadetect
    nprocess: 60
  - name: CLClusterBinningRedshiftRichness
    nprocess: 1
  - name: CLClusterShearCatalogs
    nprocess: 10   #>1 does not work with mpi
  - name: CLClusterEnsembleProfiles
    nprocess: 10
  - name: CLClusterSACC
    nprocess: 1
    aliases:
        cluster_profiles: cluster_profiles
#    - name: CLClusterDataVector
#      nprocess: 1
output_dir: /sps/lsst/groups/clusters/cl_pipeline_project/TXPipe_data/cosmodc2/outputs-022_09_cosmo/
# Put the logs from the individual stages in this directory:
log_dir: ./logs_022_09_cosmo

# Put the logs from the individual stages in this directory:
config: ./cosmodc2_config_022_09_cosmo.yml
inputs:
    # See README for paths to download these files
    shear_catalog: /sps/lsst/groups/clusters/cl_pipeline_project/TXPipe_data/cosmodc2/full/shear_catalog.hdf5
    #photometry_catalog:  /sps/lsst/users/mricci/TXPipe_data/data_link/cosmodc2/20deg2/photometry_catalog.hdf5
    fiducial_cosmology: /sps/lsst/groups/clusters/cl_pipeline_project/TXPipe_data/cosmodc2/fiducial_cosmology_022_09.yml
    calibration_table: /sps/lsst/groups/clusters/cl_pipeline_project/TXPipe_data/cosmodc2/20deg2/sample_cosmodc2_w10year_errors.dat
    spectroscopic_catalog: /sps/lsst/groups/clusters/cl_pipeline_project/TXPipe_data/cosmodc2/20deg2/spectroscopic_catalog.hdf5
    cluster_catalog: /sps/lsst/groups/clusters/cl_pipeline_project/TXPipe_data/cosmodc2/full/cluster_catalog.hdf5
    #shear_tomography_catalog: ./data/example/outputs_metadetect/shear_tomography_catalog.hdf5
    source_photoz_pdfs: /sps/lsst/groups/clusters/cl_pipeline_project/TXPipe_data/cosmodc2/outputs-full-2026/source_photoz_pdfs.hdf5
resume: true
pipeline_log: ./logs_cosmo/log_full.txt

---

id: Firecrown
modules: clpipeline
launcher:
    name: mini
    interval: 0.5
site:
    name: local
    max_threads: 4
stages:
    - name: FirecrownPipeline
      module_name: clpipeline.firecrown_pipeline
      nprocess: 1
inputs:
    clusters_sacc_file_cov: ./outputs_022_09/clusters_sacc_file_cov.sacc

# Overall configuration file 
config: ./cosmodc2_config_022_09_cosmo.yml

# If all the outputs for a stage already exist then do not re-run that stage
resume: False

# Put all the output files in this directory:
output_dir: ./outputs_022_09

# Put the logs from the individual stages in this directory:
log_dir: ./logs_022_09

---
id: TJPCov
modules: clpipeline

launcher:
    name: mini
    interval: 0.5
site:
    name: local
    max_threads: 4
stages:
    - name: TJPCovPipeline
      module_name: clpipeline.tjpcov_pipeline
      nprocess: 1
inputs:
    clusters_sacc_file: /sps/lsst/groups/clusters/cl_pipeline_project/TXPipe_data/cosmodc2/outputs-022_09_cosmo/cluster_sacc_catalog.sacc

# Overall configuration file 
config: ./cosmodc2_config_022_09_cosmo.yml


# If all the outputs for a stage already exist then do not re-run that stage
resume: False

# Put all the output files in this directory:
output_dir: ./outputs_022_09


# Put the logs from the individual stages in this directory:
log_dir: ./logs_022_09

---