name: firecrown_clp2
channels:
  - conda-forge
dependencies:
  - alabaster
  - babel
  - black
  - charset-normalizer
  - cosmosis >= 3.0
  - cosmosis-build-standard-library
  - coverage
  - cython < 3.0.0
  - dill
  - fitsio
  - flake8
  - flake8-docstrings
  - fuzzywuzzy
  - getdist
  - glib
  - idna
  - matplotlib-base
  - more-itertools
  - mypy
  - numcosmo >=0.21.1
  - numpy >= 1.23.0
  - pip
  - portalocker
  - pybobyqa
  - pyccl >= 2.8.0
  - pydantic
  - pylint
  - pytest
  - pytest-cov
  - python >= 3.10
  - pyyaml
  - requests
  - sacc >= 0.11
  - scipy < 1.14.0
  - sphinx=7.1.2
  - types-pyyaml
  - urllib3
  - pip:
    - qp-prob
    - git+https://github.com/LSSTDESC/firecrown
    - autoclasstoc
    - cobaya
    - isitgr
    - pygobject-stubs
    - git+https://github.com/LSSTDESC/CLMM.git@1.14.1
    - git+https://github.com/hellebore74/ceci
