name: firecrown_clp
channels:
  - conda-forge
dependencies:
  - alabaster
  - babel
  - black
  - charset-normalizer
  - clmm
  - compilers <= 1.8
  - cosmosis >= 3.0
  - cosmosis-build-standard-library
  - coverage
  - cython < 3.0.0
  - dill
  - fitsio
  - flake8
  - flake8-docstrings
  - fuzzywuzzy
  - getdist
  - glib
  - idna
  - matplotlib-base
  - more-itertools
  - mypy
  - numcosmo >=0.21.1
  - numpy >= 2.0, < 2.4
  - pip >= 20.1
  - portalocker
  - pybobyqa
  - pyccl >= 2.8.0
  - pydantic
  - pylint
  - pytest
  - pytest-cov
  - python >=3.11
  - pyyaml
  - requests
  - sacc >= 2.1
  - scipy
  - sphinx
  - sphinx-autoapi
  - sphinx-autodoc-typehints
  - sphinx-rtd-theme
  - sphinxcontrib-apidoc
  - tabulate
  - types-pyyaml
  - urllib3
  - jupyter
  - graphviz
  - pytest-xdist
  - hypothesis
  - plotnine < 0.15
  - rich
  - typer
  - types-requests
  - linkchecker
  - pytest-json-report
  - pip:
    - ceci >= 2.5
    - qp-prob
    - git+https://github.com/LSSTDESC/CLMM.git@1.14.6
    - git+https://github.com/LSSTDESC/firecrown
    - git+https://github.com/LSSTDESC/TJPCov.git@clustercount_cov_validation
    - autoclasstoc
    - cobaya
    - isitgr
    - pygobject-stubs
    - lsstdesc-crow
