name: firecrown_clp
channels:
  - conda-forge
dependencies:
  - alabaster
  - babel
  - black
  - charset-normalizer
  - clmm
  - compilers <= 1.8
  - cosmosis >= 3.0
  - cosmosis-build-standard-library
  - coverage
  - cython < 3.0.0
  - dill
  - fitsio
  - flake8
  - flake8-docstrings
  - fuzzywuzzy
  - getdist
  - glib
  - idna
  - matplotlib-base
  - more-itertools
  - mypy
  - numcosmo >=0.21.1
  - numpy >= 1.25.0
  - pip >= 20.1
  - portalocker
  - pybobyqa
  - pyccl >= 2.8.0
  - pydantic
  - pylint
  - pytest
  - pytest-cov
  - python >= 3.10
  - pyyaml
  - requests
  - sacc >= 0.11
  - scipy
  - sphinx
  - sphinx-autoapi
  - sphinx-autodoc-typehints
  - sphinx-rtd-theme
  - sphinxcontrib-apidoc
  - tabulate
  - types-pyyaml
  - urllib3
  - pip:
    - qp-prob
    - git+https://github.com/LSSTDESC/firecrown
    - autoclasstoc
    - cobaya
    - isitgr
    - pygobject-stubs
    - git+https://github.com/hellebore74/ceci
