# environment-perlmutter-fixed.yml
# before starting to install, we have to do `module load mpich/4.3.0`, and in the env activation, `    module load mpich/4.3.0, export MPI4PY_RC_RECV_MPROBE='False', export HDF5_USE_FILE_LOCKING=FALSE`
channels:
  - conda-forge
dependencies:
  - astropy=6.1.*
  - camb=1.5.*
  - cosmosis=3.20.*
  - cmake
  - dask=2024.5.2
  - dm-tree=0.1.9
  - fitsio=1.2.*
  # Firecrown is installed manually later in the bootstrap script
  # Force h5py to use MPI linked against mpich external (Cray)
  - h5py>=3=mpi_mpich_*
  - healpy=1.18.*
  - healsparse=1.10.*
  - jax=0.6.0
  - jaxlib=0.6.0
  - jupyter=1.0.*
  - matplotlib=3.8.*
  # Force mpi4py to use the external (system/Cray) build
  - mpi4py=4.0.*
  - mpich=4.3.0=external_*
  - namaster=2.4.*
  - numpy=2.2.*
  - pandas=2.2.*
  - psutil=5.9.*
  - pyccl=3.2.*
  - python=3.10.*
  - scikit-learn=1.5.*
  - scipy=1.13.*
  - tables-io-full=1.0.*
  - threadpoolctl=3.5.*
  - treecorr=5.0.*
  - pip=24.0.*
  - pygraphviz=1.13.*
  - qp-prob=1.0.*
  - nbconvert
  - ipykernel
  - lsstdesc-gcr-catalogs
  - guppy3
  - lsstdesc-dc2-dm-data
  - psycopg2
  - pyarrow
  - pytables
  - somoclu
  - pip:
    - git+https://github.com/LSSTDESC/TJPCov.git@clustercount_cov_validation
    - git+https://github.com/hellebore74/ceci
    - git+https://github.com/jlvdb/hyperbolic@b88b107a291fa16c2006cf971ce610248d58e94c
    - dask-mpi>=2022.4.0
    - git+https://github.com/LSSTDESC/CLMM.git@1.14.1
    - parallel-statistics==0.13
    - sacc[all]==0.14
    - glass==2023.7
    - git+https://github.com/beckermr/hybrideb@a3198ea5bc8175542b058e5c1289d910f05fd99d
    - pz-rail[algos] @ git+https://github.com/LSSTDESC/RAIL@v1.1.2
    - numpy==2.2.*          # remove this if you prefer conda numpy (kept for compatibility with some pip packages)
    - git+https://github.com/LSSTDESC/dataregistry.git

