id: configure

site: in2p3

clpipeline_dir: /sps/lsst/users/ebarroso/CLPipeline
# Directory that will contain all the files
folder: txpipe_run
analysis: cosmodc2_redmapper_full_analysis
runidentifier: cosmo # both, cosmo, mor

templatedir: ./
name: ../$FOLDER/$ANALYSIS/run_$SITE_$RUNIDENTIFIER
userworkingdir: $PWD
computationdir: $USERWORKINGDIR/$NAME

# Survey data
data: cosmodc2
datadir_full: cosmodc2/full
datadir_20deg2: cosmodc2/20deg2

# job concatenated yaml file
jobconcatyamlfile: $TEMPLATEDIR/job_concat_$SITE.yml

# Pipeline setup
txpipe_datadir:
    nersc: /global/cfs/projectdirs/lsst/groups/CL/cl_pipeline_project/TXPipe_data
    in2p3: /sps/lsst/groups/clusters/cl_pipeline_project/TXPipe_data
    local: my_data_directory

txpipe_outputdir:
    nersc: /global/cfs/projectdirs/lsst/groups/CL/cl_pipeline_project/TXPipe_data/outputs-test-auto-2026/ 
    in2p3: /sps/lsst/groups/clusters/cl_pipeline_project/TXPipe_data/cosmodc2/outputs-test-auto-2026/

txpipe_directory:
    nersc: /global/cfs/projectdirs/lsst/groups/CL/cl_pipeline_project/TXPipe
    in2p3: /sps/lsst/groups/clusters/cl_pipeline_project/TXPipe

outputdir : ./outputs_$RUNIDENTIFIER
logdir: ./logs_$RUNIDENTIFIER

config_file_generic: ./$TEMPLATEDIR/cosmodc2_config_$RUNIDENTIFIER.yml
config_file: ./config_$SITE_$RUNIDENTIFIER.yml


# Conda package directory
conda_directory:
    nersc: /global/cfs/projectdirs/lsst/groups/CL/cl_pipeline_project
    in2p3: /sps/lsst/groups/clusters/cl_pipeline_project
    local: my_conda_directory

# Batch parameters - see batch_param.yml file
batch_id: $ANALYSIS
batch_files: 
    nersc: ./$TEMPLATEDIR/launch_job_all_generic.sh
    in2p3: ./$TEMPLATEDIR/launch_job_all_generic.sh

