global:
  metacalibration: true
FirecrownPipeline:
  hmf: 'despali16'
  min_mass: 12.0
  max_mass: 15.5
  min_z: 0.2
  max_z: 0.8
  mass_def: '200c'
  use_shear_profile: true
  use_completeness: false
  use_purity: false
  use_grid: true
  is_deltasigma: true
  use_beta_interp: false
  beta_parameters: [10.0, 5.0]
  pivot_mass: 14.3
  pivot_z: 0.5
  survey_name: 'capish_dc2'
  sampler: 'emcee'
  use_cluster_counts: true
  use_mean_log_mass: false
  use_mean_deltasigma: true
  set_concentration: false
  emcee_walkers: 100
  emcee_samples: 50000
  emcee_nsteps: 20
  cosmological_parameters:
    omega_c: {'sample': true, 'values': [0.15, 0.22, 0.35]}
    sigma_8: {'sample': true, 'values': [0.7, 0.800, 0.9]}
  firecrown_parameters:
    mass_distribution_mu0: {'sample': true, 'values': [2.0, 3.3439, 10.0]}
    mass_distribution_mu1: {'sample': true, 'values': [0.5, 0.958236982, 2.0]}
    mass_distribution_mu2: {'sample': true, 'values': [-2.0, 0.0, 2.0]}
    mass_distribution_sigma0: {'sample': true, 'values': [0.1, 0.56, 2.0]}
    mass_distribution_sigma1: {'sample': true, 'values': [-0.6, 0.0, 0.3]}
    mass_distribution_sigma2: {'sample': true, 'values': [-0.5, 0.0, 2.0]}
    cluster_theory_cluster_concentration: {'sample': false, 'values': 3.8}
TJPCovPipeline:
  use_mpi: false
  do_xi: false
    #cov_type: [ClusterCountsGaussian]
    #cov_type: [ClusterMass, ClusterCountsGaussian, ClusterCountsSSC]
  cov_type: [ClusterCountsGaussian, ClusterCountsSSC]
  sel_func: false
    # sacc input file 
    # 'set' from parameters OR pass CCL cosmology object OR yaml file
  photo-z:
        # from DES Y1
    sigma_0: 0.05
  mor_parameters:
        #halo mass function parameters
    mass_func: 'Despali16'
    mass_def: '200c'
    halo_bias: 'Tinker10'
    min_halo_mass: 1.0e12
    max_halo_mass: 3.16e15
        #richness-mass relation parameters (from eq (14) in https://arxiv.org/pdf/1904.07524):
    m_pivot: 14.3
    z_pivot: 0.5
    mu_p0: 3.34
    mu_p1: 0.99
    mu_p2: 0.0
    sigma_p0: 0.56
    sigma_p1: 0.0
    sigma_p2: 0.0
