id: TJPCov
modules: clpipeline
launcher:
    name: mini
    interval: 0.5
site:
    name: local
    max_threads: 4
stages:
  - name: TJPCovPipeline
    module_name: clpipeline.tjpcov_pipeline
    nprocess: 1
inputs:
    clusters_sacc_file: ../mock_DC2like_cluster_sacc.sacc
config: ./config_in2p3_both.yml
resume: false
output_dir: ./outputs_both
log_dir: ./logs_both
