id: TJPCov
modules: clpipeline
launcher:
    name: mini
    interval: 0.5
site:
    name: local
    max_threads: 4
stages:
  - name: TJPCovPipeline
    module_name: clpipeline.tjpcov_pipeline
    nprocess: 1
inputs:
    clusters_sacc_file: /sps/lsst/groups/clusters/cl_pipeline_project/TXPipe_data/cosmodc2/outputs-full-2026//cluster_sacc_catalog.sacc
config: ./config_in2p3_cosmo.yml
resume: false
output_dir: ./outputs_cosmo
log_dir: ./logs_cosmo
