#this step depends on where you run
#for CCin2p3
site:
    name: local
    max_threads: 4
#site:
#    name: cori-batch
#    image: ghcr.io/lsstdesc/txpipe-dev
#all the following steps should not depend on where you run 
launcher:
    name: mini
    interval: 0.5
modules: >
    txpipe
    rail.estimation.algos.bpz_lite
python_paths: []
stages:
  - name: TXSourceSelectorMetadetect
    nprocess: 30
  - name: BPZliteInformer
    nprocess: 1
    aliases:
        input: spectroscopic_catalog
        model: photoz_model
  - name: BPZliteEstimator
    nprocess: 30
    aliases:
        model: photoz_model
        input: shear_catalog
        output: source_photoz_pdfs
  - name: CLClusterBinningRedshiftRichness
    nprocess: 1
  - name: CLClusterShearCatalogs
    nprocess: 30   #>1 does not work with mpi
  - name: CLClusterEnsembleProfiles
    nprocess: 10
#    - name: CLClusterDataVector
#      nprocess: 1
output_dir: ./tests/outputs/cosmodc2

# Put the logs from the individual stages in this directory:
log_dir: ./tests/logs/cosmodc2

# Put the logs from the individual stages in this directory:
config: ./inputs_config/cosmodc2/config-20deg2-CL.yml
inputs:
    # See README for paths to download these files
    shear_catalog: /sps/lsst/groups/clusters/cl_pipeline_project/TXPipe_data/cosmodc2/20deg2/shear_catalog.hdf5
    #photometry_catalog:  /sps/lsst/users/mricci/TXPipe_data/data_link/cosmodc2/20deg2/photometry_catalog.hdf5
    fiducial_cosmology: /sps/lsst/groups/clusters/cl_pipeline_project/TXPipe_data/cosmodc2/fiducial_cosmology.yml
    calibration_table: /sps/lsst/groups/clusters/cl_pipeline_project/TXPipe_data/cosmodc2/20deg2/sample_cosmodc2_w10year_errors.dat
    spectroscopic_catalog: /sps/lsst/groups/clusters/cl_pipeline_project/TXPipe_data/cosmodc2/20deg2/spectroscopic_catalog.hdf5
    cluster_catalog: /sps/lsst/groups/clusters/cl_pipeline_project/TXPipe_data/cosmodc2/20deg2/cluster_catalog.hdf5
    #shear_tomography_catalog: ./data/example/outputs_metadetect/shear_tomography_catalog.hdf5
    #source_photoz_pdfs: ./data/example/inputs/photoz_pdfs.hdf5
resume: true
pipeline_log: ./tests/logs/cosmodc2/log_20deg2.txt
