global:
    metacalibration: True
FirecrownPipeline:
    hmf: 'despali16'
    min_mass: 13.0
    max_mass: 16.0
    min_z: 0.2
    max_z: 0.8
    pivot_mass: 14.5
    pivot_z: 0.6
    survey_name: "cosmodc2_wazp"
    sampler: 'emcee'
    use_cluster_counts: True
    use_mean_log_mass: False
    use_mean_deltasigma: False
    set_concentration: False
    emcee_walkers: 20
    emcee_samples: 4000
    emcee_nsteps: 10
    cosmological_parameters:
        omega_c: {'sample': True, 'values': [0.1552, 0.2052, 0.3552]}
        sigma_8: {'sample': True, 'values': [0.7, 0.800, 0.9]}
        omega_k: {'sample': False, 'values': 0.0}
        omega_b: {'sample': False, 'values': 0.0448}
        tau: {'sample': False, 'values': 0.08}
        n_s: {'sample': False, 'values': 0.963}
        h0: {'sample': False, 'values': 0.71}
        w: {'sample': False, 'values': -1.0}
        wa: {'sample': False, 'values': 0.0}
    firecrown_parameters:
        mu_p0: {'sample': True, 'values': [2.0, 3.0, 4.0]}
        mu_p1: {'sample': True, 'values': [0.4, 0.8, 1.2]}
        mu_p2: {'sample': True, 'values': [-0.6, -0.3, 0.6]}
        sigma_p0: {'sample': True, 'values': [0.02, 0.3, 0.6]}
        sigma_p1: {'sample': True, 'values': [-0.1, -0.03, 0.1]}
        sigma_p2: {'sample': True, 'values': [-0.1, 0.06, 0.1]}
TJPCovPipeline:
    use_mpi: False
    do_xi: False
    #cov_type: [ClusterCountsGaussian]
    #cov_type: [ClusterMass, ClusterCountsGaussian, ClusterCountsSSC]
    cov_type: [ClusterCountsGaussian, ClusterCountsSSC]
    # sacc input file 
    # 'set' from parameters OR pass CCL cosmology object OR yaml file
    cosmo: 'set' 
    fsky: 0.3
    parameters:
        # Not used for while (read by ccl.cosmo):
        Omega_c: 0.22
        Omega_b: 0.0448
        h: 0.71
        n_s: 0.963
        sigma8: 0.8
        w0: -1
        wa: 0
        transfer_function: 'boltzmann_camb'
    photo-z:
        # from DES Y1
        sigma_0: 0.005
    mor_parameters:
        #halo mass function parameters
        mass_func: 'Despali16'
        mass_def: '200c'
        halo_bias: 'Tinker10'
        min_halo_mass: 1.0e13
        max_halo_mass: 1.0e16
        #richness-mass relation parameters (from eq (14) in https://arxiv.org/pdf/1904.07524):
        m_pivot: 14.5
        z_pivot: 0.6
        mu_p0: 3.35
        mu_p1: 0.968
        mu_p2: 0.06
        sigma_p0: 0.56
        sigma_p1: 0.043
        sigma_p2: -0.05








